version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/server #image build src
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/client
    environment:
      - NODE_ENV=production
